apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: meeting-server-503
spec:
  destination:
    name: meeting-server
  precedence: 10
  route:
  - labels:
      version: "1.0"
  httpFault:
    delay:
      percent: 100
      fixedDelay: 2s
