apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRole
metadata:
  name: viewer
  namespace: default
spec:
  rules:
  - services: ["*"]
    methods: ["GET", "HEAD"]
    constraints:
    - key: "destination.name"
      values: ["guestbook-service", "helloworld-service", "guestbook-ui"]
---
apiVersion: rbac.istio.io/v1alpha1
kind: ServiceRoleBinding
metadata:
  name: bind-viewer
  namespace: default
spec:
  subjects:
  - properties:
      source.namespace: istio-system
  - properties:
      source.namespace: default
  roleRef:
    kind: ServiceRole
    name: viewer
